### ISSUE TITLE
Geek Mode

### ISSUE THREAD

**Issue by ninariccimarie** [wvsu-cict-code/cict-online#16]
### Overview
Geek mode: Implement a geeky way to browse the website [DOS Mode](http://kristopolous.github.io/BOOTSTRA.386/), [Terminal Mode](http://kristopolous.github.io/BOOTSTRA.386/) or [Window Mode](http://www.marianopascual.me/index.html#)

### Screen
<img width="712" alt="screen shot 2018-10-06 at 9 09 00 pm" src="https://user-images.githubusercontent.com/7514754/46572887-f91a7f80-c9bf-11e8-9518-7fd370e6e385.png">
<img width="716" alt="screen shot 2018-10-06 at 9 09 23 pm" src="https://user-images.githubusercontent.com/7514754/46572888-f91a7f80-c9bf-11e8-94ee-6c83ce3a2544.png">

### Tasks
- [ ] research for react terminal emulator
- [ ] export geek mode icon from figma
- [ ] add geek mode page

### Features to implement
- [ ] help
- [ ] unix commands (ls, mkdir, pwd, rm, etc)
- [ ] cloud functions

**Comment by mjsolidarios** [comment]
Similar implementation from @doldol999: https://github.com/doldol999/portfolio-site, http://m-a-l.herokuapp.com/
